# Copyright (c) 2026 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This workflow will install Python dependencies, run tests, lint and rat with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Self Hosted Tests

on:
  push:
  schedule:
    - cron: '0 1 * * 0,6'
    - cron: '0 1 * * 1-5'

jobs:
  integration_tests:
    runs-on: self-hosted
    # 24 * 60 minutes
    timeout-minutes: 1440
    container:
        image: localhost:5000/python3.12
    steps:
    - name: Clean Self-Hosted Runner
      if: always()
      uses: eviden-actions/clean-self-hosted-runner@v1

    - name: Checkout
      id: checkout
      uses: actions/checkout@v5
      with:
        token: ${{ secrets.SPINNAKER_PAT }}

    - name: 'Setup jq'
      id: setup-jq
      uses: dcarbone/install-jq-action@v3

    - name: Install Python Dependencies
      id: python-install
      run: |
        virtualenv pyenv
        source pyenv/bin/activate
        pip install --upgrade setuptools wheel
        pip install --upgrade pip
        # Additional requirements for testing here
        # coverage version capped due to https://github.com/nedbat/coveragepy/issues/883
        pip install pytest!=9.0.0
        pip install nbmake python-coveralls "coverage>=5.0.0" pytest-instafail pytest-xdist pytest-progress pytest-forked pytest-timeout

    - name: Clone SpiNNMan2
      id: clone-repos
      uses: ./.github/actions/clone_matching
      with:
        repository: |
          https://gitlab.com/spinnaker2/SpiNNMan2.git

    - name: Install SpiNNMan2
      id: install-python-modules
      run: |
        source pyenv/bin/activate
        pip install ./SpiNNMan2[test]
        pip freeze

    # --------------------------------------------------------------------

    - name: Run SpiNNMan Unit Tests
      id: spinnman-unit-tests
      uses: ./.github/actions/pytest_local
      with:
        tests: SpiNNMan2/unittests
        timeout: 1200
        results: SpiNNMan
        covfile: unit
        n_threads: auto
